//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalar.
        /// </summary>
        internal static string A2HSButton {
            get {
                return ResourceManager.GetString("A2HSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea cerrar su sesión? Si existieran operaciones pendientes de conexión serán canceladas..
        /// </summary>
        internal static string alertConfirmLogout {
            get {
                return ResourceManager.GetString("alertConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string alertConfirmLogoutYes {
            get {
                return ResourceManager.GetString("alertConfirmLogoutYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, se ha producido un error. Por favor intente nuevamente más tarde..
        /// </summary>
        internal static string alertErrorBody {
            get {
                return ResourceManager.GetString("alertErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error al intentar completar el campo &apos;{0}&apos;.
        /// </summary>
        internal static string alertErrorField {
            get {
                return ResourceManager.GetString("alertErrorField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado correctamente el proceso de negocio con el cual interactuar. Por favor contacte con su administrador..
        /// </summary>
        internal static string alertErrorPngIdConfig {
            get {
                return ResourceManager.GetString("alertErrorPngIdConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string alertErrorTitle {
            get {
                return ResourceManager.GetString("alertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se están visualizando los #COUNT# elementos más recientes.
        /// </summary>
        internal static string alertInfoExistsMoreElements {
            get {
                return ResourceManager.GetString("alertInfoExistsMoreElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener conexión a Internet para realizar el primer inicio de sesión.
        /// </summary>
        internal static string alertLoginNotNetworkFirstLogin {
            get {
                return ResourceManager.GetString("alertLoginNotNetworkFirstLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin conexión a Internet.
        /// </summary>
        internal static string alertNotNetworkTitle {
            get {
                return ResourceManager.GetString("alertNotNetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación será confirmada cuando se recupere conexión a Internet.
        /// </summary>
        internal static string alertPendingActivityEndBody {
            get {
                return ResourceManager.GetString("alertPendingActivityEndBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        internal static string alertPendingActivityEndTitle {
            get {
                return ResourceManager.GetString("alertPendingActivityEndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &apos;{0}&apos; es requerido.
        /// </summary>
        internal static string alertRequiredField {
            get {
                return ResourceManager.GetString("alertRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta operación requiere conexión a Internet en este momento.
        /// </summary>
        internal static string alertRequiredNetworkFirstTimeBody {
            get {
                return ResourceManager.GetString("alertRequiredNetworkFirstTimeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requiere conexión a Internet.
        /// </summary>
        internal static string alertRequiredNetworkFirstTimeTitle {
            get {
                return ResourceManager.GetString("alertRequiredNetworkFirstTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar una contraseña.
        /// </summary>
        internal static string alertRequiredPassword {
            get {
                return ResourceManager.GetString("alertRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requerido.
        /// </summary>
        internal static string alertRequiredTitle {
            get {
                return ResourceManager.GetString("alertRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar un nombre de usuario.
        /// </summary>
        internal static string alertRequiredUserName {
            get {
                return ResourceManager.GetString("alertRequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación ha sido confirmada con éxito.
        /// </summary>
        internal static string alertSuccessActivityEndBody {
            get {
                return ResourceManager.GetString("alertSuccessActivityEndBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han completado operaciones que estaban pendientes de conexión.
        /// </summary>
        internal static string alertSuccessActivityEndPending {
            get {
                return ResourceManager.GetString("alertSuccessActivityEndPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Felicitaciones.
        /// </summary>
        internal static string alertSuccessActivityEndTitle {
            get {
                return ResourceManager.GetString("alertSuccessActivityEndTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Instancia desbloqueda.
        /// </summary>
        internal static string alertSuccessUnlockInstance
        {
            get
            {
                return ResourceManager.GetString("alertSuccessUnlockInstance", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        internal static string alertUserOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("alertUserOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En este momento no dispone de conexión a Internet.
        /// </summary>
        internal static string alertWarningNotNetworkFormBody {
            get {
                return ResourceManager.GetString("alertWarningNotNetworkFormBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin conexión a Internet.
        /// </summary>
        internal static string alertWarningNotNetworkFormTitle {
            get {
                return ResourceManager.GetString("alertWarningNotNetworkFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string FormButtonAccept {
            get {
                return ResourceManager.GetString("FormButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string FormButtonCancel {
            get {
                return ResourceManager.GetString("FormButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a por.
        /// </summary>
        internal static string lblBy {
            get {
                return ResourceManager.GetString("lblBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen elementos pendientes.
        /// </summary>
        internal static string lblInboxEmpty {
            get {
                return ResourceManager.GetString("lblInboxEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string lblNewElement {
            get {
                return ResourceManager.GetString("lblNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string LoginTitleWelcome {
            get {
                return ResourceManager.GetString("LoginTitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string LoginUserName {
            get {
                return ResourceManager.GetString("LoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pectra.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a espere por favor....
        /// </summary>
        internal static string WaitingMessage {
            get {
                return ResourceManager.GetString("WaitingMessage", resourceCulture);
            }
        }
    }
}
