//------------------------------------------------------------------------------
// <auto-generated>
//   Este codigo fue generado por Pectra Forms
// 
//   Cambios en este archivo pueden ocasionar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

using log4net;
using PectraForms.WebApplication.Models;
using System.Reflection;
using System.Web.Mvc;

namespace PectraForms.WebApplication.Controllers
{
    public class _BaseController : Controller
    {
        private static readonly ILog m_log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);

        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            filterContext.ExceptionHandled = true;

            // Log error
            m_log.Error(filterContext.Exception.Message, filterContext.Exception);

            ViewDataDictionary oViewData = new ViewDataDictionary();
            oViewData.Model = new TransactionCompletedViewModel()
            {
                Message = Resources.Resource.Error,
                MessageDetail = Resources.Resource.ErrorDetail
            };

            filterContext.Result = new ViewResult()
            {
                ViewName = "Error",
                ViewData = oViewData
            };
        }
    }
}