//------------------------------------------------------------------------------
// <auto-generated>
//   Este codigo fue generado por Pectra Forms
// 
//   Cambios en este archivo pueden ocasionar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace PectraForms.WebApplication.BackEnd.BusinessEntities
{
    public class AdjuntosBE
    {
        public int IdAdjunto { get; set; }

        public string IdGrupo { get; set; }

        public string Descripcion { get; set; }

        public byte[] Archivo { get; set; }

        public string NombreArchivo { get; set; }

        public string Tipo { get; set; }

        public string IdUsuario { get; set; }

        public string IdPerfil { get; set; }

        public int? IdRelacion { get; set; }

    }
}