//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PectraForms.WebApplication.BackEnd.API.PectraGDReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PectraForms.WebApplication.BackEnd.API.PectraGDReference.Language DefaultLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PectraForms.WebApplication.BackEnd.API.PectraGDReference.OperationalUnit DefaultOperationalUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PectraForms.WebApplication.BackEnd.API.PectraGDReference.Organization DefaultOrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PectraForms.WebApplication.BackEnd.API.PectraGDReference.Profile DefaultProfileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.Language DefaultLanguage {
            get {
                return this.DefaultLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultLanguageField, value) != true)) {
                    this.DefaultLanguageField = value;
                    this.RaisePropertyChanged("DefaultLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.OperationalUnit DefaultOperationalUnit {
            get {
                return this.DefaultOperationalUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultOperationalUnitField, value) != true)) {
                    this.DefaultOperationalUnitField = value;
                    this.RaisePropertyChanged("DefaultOperationalUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.Organization DefaultOrganization {
            get {
                return this.DefaultOrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultOrganizationField, value) != true)) {
                    this.DefaultOrganizationField = value;
                    this.RaisePropertyChanged("DefaultOrganization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.Profile DefaultProfile {
            get {
                return this.DefaultProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultProfileField, value) != true)) {
                    this.DefaultProfileField = value;
                    this.RaisePropertyChanged("DefaultProfile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class Language : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageIdField, value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationalUnit", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class OperationalUnit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class Organization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrgUoProf", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts.OrgUoProf")]
    [System.SerializableAttribute()]
    public partial class OrgUoProf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PectraForms.WebApplication.BackEnd.API.PectraGDReference.OrganizationUo> OrganizationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PectraForms.WebApplication.BackEnd.API.PectraGDReference.OrganizationUo> Organizations {
            get {
                return this.OrganizationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationsField, value) != true)) {
                    this.OrganizationsField = value;
                    this.RaisePropertyChanged("Organizations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationUo", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts.OrgUoProf")]
    [System.SerializableAttribute()]
    public partial class OrganizationUo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PectraForms.WebApplication.BackEnd.API.PectraGDReference.Organization OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PectraForms.WebApplication.BackEnd.API.PectraGDReference.OperationalUnitProf> OperationalUnitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.Organization Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Collections.Generic.List<PectraForms.WebApplication.BackEnd.API.PectraGDReference.OperationalUnitProf> OperationalUnits {
            get {
                return this.OperationalUnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationalUnitsField, value) != true)) {
                    this.OperationalUnitsField = value;
                    this.RaisePropertyChanged("OperationalUnits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationalUnitProf", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts.OrgUoProf")]
    [System.SerializableAttribute()]
    public partial class OperationalUnitProf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PectraForms.WebApplication.BackEnd.API.PectraGDReference.OperationalUnit OperationalUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgUoDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PectraForms.WebApplication.BackEnd.API.PectraGDReference.Prof> ProfilesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.OperationalUnit OperationalUnit {
            get {
                return this.OperationalUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationalUnitField, value) != true)) {
                    this.OperationalUnitField = value;
                    this.RaisePropertyChanged("OperationalUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgUoDescription {
            get {
                return this.OrgUoDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgUoDescriptionField, value) != true)) {
                    this.OrgUoDescriptionField = value;
                    this.RaisePropertyChanged("OrgUoDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PectraForms.WebApplication.BackEnd.API.PectraGDReference.Prof> Profiles {
            get {
                return this.ProfilesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilesField, value) != true)) {
                    this.ProfilesField = value;
                    this.RaisePropertyChanged("Profiles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prof", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts.OrgUoProf")]
    [System.SerializableAttribute()]
    public partial class Prof : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PectraForms.WebApplication.BackEnd.API.PectraGDReference.Profile ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DefaultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.Profile Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterface.GeneralDomain.DataContra" +
        "cts")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UsrDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UsrDateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] UsrDefinitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrEMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UsrLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UsrLastUpdateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrPicContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] UsrPictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrPwdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UsrDate {
            get {
                return this.UsrDateField;
            }
            set {
                if ((this.UsrDateField.Equals(value) != true)) {
                    this.UsrDateField = value;
                    this.RaisePropertyChanged("UsrDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UsrDateUtc {
            get {
                return this.UsrDateUtcField;
            }
            set {
                if ((this.UsrDateUtcField.Equals(value) != true)) {
                    this.UsrDateUtcField = value;
                    this.RaisePropertyChanged("UsrDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] UsrDefinition {
            get {
                return this.UsrDefinitionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrDefinitionField, value) != true)) {
                    this.UsrDefinitionField = value;
                    this.RaisePropertyChanged("UsrDefinition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrEMail {
            get {
                return this.UsrEMailField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrEMailField, value) != true)) {
                    this.UsrEMailField = value;
                    this.RaisePropertyChanged("UsrEMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrFirstName {
            get {
                return this.UsrFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrFirstNameField, value) != true)) {
                    this.UsrFirstNameField = value;
                    this.RaisePropertyChanged("UsrFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrGender {
            get {
                return this.UsrGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrGenderField, value) != true)) {
                    this.UsrGenderField = value;
                    this.RaisePropertyChanged("UsrGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrId {
            get {
                return this.UsrIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrIdField, value) != true)) {
                    this.UsrIdField = value;
                    this.RaisePropertyChanged("UsrId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrLastName {
            get {
                return this.UsrLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrLastNameField, value) != true)) {
                    this.UsrLastNameField = value;
                    this.RaisePropertyChanged("UsrLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UsrLastUpdate {
            get {
                return this.UsrLastUpdateField;
            }
            set {
                if ((this.UsrLastUpdateField.Equals(value) != true)) {
                    this.UsrLastUpdateField = value;
                    this.RaisePropertyChanged("UsrLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UsrLastUpdateUtc {
            get {
                return this.UsrLastUpdateUtcField;
            }
            set {
                if ((this.UsrLastUpdateUtcField.Equals(value) != true)) {
                    this.UsrLastUpdateUtcField = value;
                    this.RaisePropertyChanged("UsrLastUpdateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrPicContentType {
            get {
                return this.UsrPicContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrPicContentTypeField, value) != true)) {
                    this.UsrPicContentTypeField = value;
                    this.RaisePropertyChanged("UsrPicContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] UsrPicture {
            get {
                return this.UsrPictureField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrPictureField, value) != true)) {
                    this.UsrPictureField = value;
                    this.RaisePropertyChanged("UsrPicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrPwd {
            get {
                return this.UsrPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrPwdField, value) != true)) {
                    this.UsrPwdField = value;
                    this.RaisePropertyChanged("UsrPwd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PectraGDReference.IGDService")]
    public interface IGDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/Login", ReplyAction="http://tempuri.org/IGDService/LoginResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginResponse Login(PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/LoginWindowsSecurity", ReplyAction="http://tempuri.org/IGDService/LoginWindowsSecurityResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginResponse LoginWindowsSecurity(PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginWindowsSecurityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/LoginWindowsSecurityWithLanguage", ReplyAction="http://tempuri.org/IGDService/LoginWindowsSecurityWithLanguageResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginResponse LoginWindowsSecurityWithLanguage(PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/Logout", ReplyAction="http://tempuri.org/IGDService/LogoutResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.LogoutResponse Logout(PectraForms.WebApplication.BackEnd.API.PectraGDReference.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/GetServices", ReplyAction="http://tempuri.org/IGDService/GetServicesResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetServicesResponse GetServices(PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetServicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/GetDefaultLanguage", ReplyAction="http://tempuri.org/IGDService/GetDefaultLanguageResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetDefaultLanguageResponse GetDefaultLanguage(PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetDefaultLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/GetOrgUoProf", ReplyAction="http://tempuri.org/IGDService/GetOrgUoProfResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetOrgUoProfResponse GetOrgUoProf(PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetOrgUoProfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/AddPropPrfGetOne", ReplyAction="http://tempuri.org/IGDService/AddPropPrfGetOneResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropPrfGetOneResponse AddPropPrfGetOne(PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropPrfGetOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/AddPropDefGetOne", ReplyAction="http://tempuri.org/IGDService/AddPropDefGetOneResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropDefGetOneResponse AddPropDefGetOne(PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropDefGetOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/AddPropUsrGetOne", ReplyAction="http://tempuri.org/IGDService/AddPropUsrGetOneResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropUsrGetOneResponse AddPropUsrGetOne(PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropUsrGetOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/RightDefGetOne", ReplyAction="http://tempuri.org/IGDService/RightDefGetOneResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.RightDefGetOneResponse RightDefGetOne(PectraForms.WebApplication.BackEnd.API.PectraGDReference.RightDefGetOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/UsrGetOneUser", ReplyAction="http://tempuri.org/IGDService/UsrGetOneUserResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.UsrGetOneUserResponse UsrGetOneUser(PectraForms.WebApplication.BackEnd.API.PectraGDReference.UsrGetOneUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGDService/UsrChangePassword", ReplyAction="http://tempuri.org/IGDService/UsrChangePasswordResponse")]
        PectraForms.WebApplication.BackEnd.API.PectraGDReference.UsrChangePasswordResponse UsrChangePassword(PectraForms.WebApplication.BackEnd.API.PectraGDReference.UsrChangePasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string UsrPwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LanguageId;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string UsrId, string UsrPwd, string LanguageId) {
            this.UsrId = UsrId;
            this.UsrPwd = UsrPwd;
            this.LanguageId = LanguageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.UserInfo User;
        
        public LoginResponse() {
        }
        
        public LoginResponse(string SessionToken, PectraForms.WebApplication.BackEnd.API.PectraGDReference.UserInfo User) {
            this.SessionToken = SessionToken;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginWindowsSecurityRequest {
        
        public LoginWindowsSecurityRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LanguageId;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(string SessionToken, string UsrId, string LanguageId) {
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.LanguageId = LanguageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogoutResponse {
        
        public LogoutResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServicesRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetServicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LanguageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string OrgId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string UoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ProfId;
        
        public GetServicesRequest() {
        }
        
        public GetServicesRequest(string SessionToken, string UsrId, string LanguageId, string OrgId, string UoId, string ProfId) {
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.LanguageId = LanguageId;
            this.OrgId = OrgId;
            this.UoId = UoId;
            this.ProfId = ProfId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServicesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetServicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<PectraForms.WebApplication.BackEnd.API.PectraGDReference.Service> Servicios;
        
        public GetServicesResponse() {
        }
        
        public GetServicesResponse(System.Collections.Generic.List<PectraForms.WebApplication.BackEnd.API.PectraGDReference.Service> Servicios) {
            this.Servicios = Servicios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDefaultLanguageRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDefaultLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LanguageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ProfId;
        
        public GetDefaultLanguageRequest() {
        }
        
        public GetDefaultLanguageRequest(string SessionToken, string UsrId, string LanguageId, string ProfId) {
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.LanguageId = LanguageId;
            this.ProfId = ProfId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDefaultLanguageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDefaultLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.Language Language;
        
        public GetDefaultLanguageResponse() {
        }
        
        public GetDefaultLanguageResponse(PectraForms.WebApplication.BackEnd.API.PectraGDReference.Language Language) {
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrgUoProfRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrgUoProfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LanguageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<int> PngId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Nullable<int> VersionId;
        
        public GetOrgUoProfRequest() {
        }
        
        public GetOrgUoProfRequest(string SessionToken, string UsrId, string LanguageId, System.Nullable<int> PngId, System.Nullable<int> VersionId) {
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.LanguageId = LanguageId;
            this.PngId = PngId;
            this.VersionId = VersionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrgUoProfResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrgUoProfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.OrgUoProf OrgUoProf;
        
        public GetOrgUoProfResponse() {
        }
        
        public GetOrgUoProfResponse(PectraForms.WebApplication.BackEnd.API.PectraGDReference.OrgUoProf OrgUoProf) {
            this.OrgUoProf = OrgUoProf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPropPrfGetOneRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPropPrfGetOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string PrfId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string GrpId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LanguageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ItemId;
        
        public AddPropPrfGetOneRequest() {
        }
        
        public AddPropPrfGetOneRequest(string PrfId, string SessionToken, string UsrId, string GrpId, string LanguageId, string ItemId) {
            this.PrfId = PrfId;
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.GrpId = GrpId;
            this.LanguageId = LanguageId;
            this.ItemId = ItemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPropPrfGetOneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPropPrfGetOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddPropValue;
        
        public AddPropPrfGetOneResponse() {
        }
        
        public AddPropPrfGetOneResponse(string AddPropValue) {
            this.AddPropValue = AddPropValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPropDefGetOneRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPropDefGetOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ItemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LanguageId;
        
        public AddPropDefGetOneRequest() {
        }
        
        public AddPropDefGetOneRequest(string GroupId, string SessionToken, string UsrId, string ItemId, string LanguageId) {
            this.GroupId = GroupId;
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.ItemId = ItemId;
            this.LanguageId = LanguageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPropDefGetOneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPropDefGetOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DefaultAddPropValue;
        
        public AddPropDefGetOneResponse() {
        }
        
        public AddPropDefGetOneResponse(string DefaultAddPropValue) {
            this.DefaultAddPropValue = DefaultAddPropValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPropUsrGetOneRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPropUsrGetOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ItemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LanguageId;
        
        public AddPropUsrGetOneRequest() {
        }
        
        public AddPropUsrGetOneRequest(string GroupId, string SessionToken, string UsrId, string ItemId, string LanguageId) {
            this.GroupId = GroupId;
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.ItemId = ItemId;
            this.LanguageId = LanguageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPropUsrGetOneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPropUsrGetOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddPropValue;
        
        public AddPropUsrGetOneResponse() {
        }
        
        public AddPropUsrGetOneResponse(string AddPropValue) {
            this.AddPropValue = AddPropValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RightDefGetOneRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RightDefGetOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ItemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LanguageId;
        
        public RightDefGetOneRequest() {
        }
        
        public RightDefGetOneRequest(string GroupId, string SessionToken, string UsrId, string ItemId, string LanguageId) {
            this.GroupId = GroupId;
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.ItemId = ItemId;
            this.LanguageId = LanguageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RightDefGetOneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RightDefGetOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RightDefaultValue;
        
        public RightDefGetOneResponse() {
        }
        
        public RightDefGetOneResponse(string RightDefaultValue) {
            this.RightDefaultValue = RightDefaultValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsrGetOneUserRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsrGetOneUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LanguageId;
        
        public UsrGetOneUserRequest() {
        }
        
        public UsrGetOneUserRequest(string SessionToken, string UsrId, string LanguageId) {
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.LanguageId = LanguageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsrGetOneUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsrGetOneUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.User User;
        
        public UsrGetOneUserResponse() {
        }
        
        public UsrGetOneUserResponse(PectraForms.WebApplication.BackEnd.API.PectraGDReference.User User) {
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsrChangePasswordRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsrChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CurrentPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UsrId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string LanguageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string NewPassword;
        
        public UsrChangePasswordRequest() {
        }
        
        public UsrChangePasswordRequest(string CurrentPassword, string SessionToken, string UsrId, string LanguageId, string NewPassword) {
            this.CurrentPassword = CurrentPassword;
            this.SessionToken = SessionToken;
            this.UsrId = UsrId;
            this.LanguageId = LanguageId;
            this.NewPassword = NewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsrChangePasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsrChangePasswordResponse {
        
        public UsrChangePasswordResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGDServiceChannel : PectraForms.WebApplication.BackEnd.API.PectraGDReference.IGDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GDServiceClient : System.ServiceModel.ClientBase<PectraForms.WebApplication.BackEnd.API.PectraGDReference.IGDService>, PectraForms.WebApplication.BackEnd.API.PectraGDReference.IGDService {
        
        public GDServiceClient() {
        }
        
        public GDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginResponse Login(PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginResponse LoginWindowsSecurity(PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginWindowsSecurityRequest request) {
            return base.Channel.LoginWindowsSecurity(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginResponse LoginWindowsSecurityWithLanguage(PectraForms.WebApplication.BackEnd.API.PectraGDReference.LoginRequest request) {
            return base.Channel.LoginWindowsSecurityWithLanguage(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.LogoutResponse Logout(PectraForms.WebApplication.BackEnd.API.PectraGDReference.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetServicesResponse GetServices(PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetServicesRequest request) {
            return base.Channel.GetServices(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetDefaultLanguageResponse GetDefaultLanguage(PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetDefaultLanguageRequest request) {
            return base.Channel.GetDefaultLanguage(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetOrgUoProfResponse GetOrgUoProf(PectraForms.WebApplication.BackEnd.API.PectraGDReference.GetOrgUoProfRequest request) {
            return base.Channel.GetOrgUoProf(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropPrfGetOneResponse AddPropPrfGetOne(PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropPrfGetOneRequest request) {
            return base.Channel.AddPropPrfGetOne(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropDefGetOneResponse AddPropDefGetOne(PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropDefGetOneRequest request) {
            return base.Channel.AddPropDefGetOne(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropUsrGetOneResponse AddPropUsrGetOne(PectraForms.WebApplication.BackEnd.API.PectraGDReference.AddPropUsrGetOneRequest request) {
            return base.Channel.AddPropUsrGetOne(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.RightDefGetOneResponse RightDefGetOne(PectraForms.WebApplication.BackEnd.API.PectraGDReference.RightDefGetOneRequest request) {
            return base.Channel.RightDefGetOne(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.UsrGetOneUserResponse UsrGetOneUser(PectraForms.WebApplication.BackEnd.API.PectraGDReference.UsrGetOneUserRequest request) {
            return base.Channel.UsrGetOneUser(request);
        }
        
        public PectraForms.WebApplication.BackEnd.API.PectraGDReference.UsrChangePasswordResponse UsrChangePassword(PectraForms.WebApplication.BackEnd.API.PectraGDReference.UsrChangePasswordRequest request) {
            return base.Channel.UsrChangePassword(request);
        }
    }
}
