//------------------------------------------------------------------------------
// <auto-generated>
//   Este codigo fue generado por Pectra Forms
// 
//   Cambios en este archivo pueden ocasionar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web.Mvc;

namespace PectraForms.PWA.Controllers
{
    public class DefaultController : Controller
    {
        public ActionResult Index()
        {
            string szUrlContent;
            const string DEFAULTCONTROLLER = "Default";

            // Url Content in IIS
            szUrlContent = Url.Content("~/" + DEFAULTCONTROLLER);
            if (szUrlContent.EndsWith("/") == true)
                szUrlContent = szUrlContent.Remove(szUrlContent.Length);

            if (Request.RawUrl != szUrlContent)
            {
                string szRedirect = Url.Action("Index", DEFAULTCONTROLLER, null, Request.Url.Scheme);

                if (szRedirect.EndsWith("/"))
                    szRedirect = szRedirect.Remove(szRedirect.Length - 1);

                if (szRedirect.Contains(DEFAULTCONTROLLER) == false)
                    szRedirect += "/" + DEFAULTCONTROLLER;

                return Redirect(szRedirect);
            }
            else
                return View();
        }
    }
}