//------------------------------------------------------------------------------
// <auto-generated>
//   Este codigo fue generado por Pectra Forms
// 
//   Cambios en este archivo pueden ocasionar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web.Mvc;

namespace PectraForms.PWA.Controllers
{
    public class InboxController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}