//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar archivo.
        /// </summary>
        internal static string btnAddFile {
            get {
                return ResourceManager.GetString("btnAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subiendo archivo...
        /// </summary>
        internal static string btnAddFileProgress {
            get {
                return ResourceManager.GetString("btnAddFileProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string btnSeleccionar {
            get {
                return ResourceManager.GetString("btnSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error. Intente nuevamente más tarde..
        /// </summary>
        internal static string ErrorDetail {
            get {
                return ResourceManager.GetString("ErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntos.
        /// </summary>
        internal static string lblAttachments {
            get {
                return ResourceManager.GetString("lblAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma eliminación.
        /// </summary>
        internal static string lblConfirmarEliminacionAdjunto {
            get {
                return ResourceManager.GetString("lblConfirmarEliminacionAdjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string lblEliminar {
            get {
                return ResourceManager.GetString("lblEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        internal static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo a adjuntar.
        /// </summary>
        internal static string lblFileToAttach {
            get {
                return ResourceManager.GetString("lblFileToAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando....
        /// </summary>
        internal static string lblLoading {
            get {
                return ResourceManager.GetString("lblLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string lblSearchTitle {
            get {
                return ResourceManager.GetString("lblSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar un archivo....
        /// </summary>
        internal static string lblSelectFile {
            get {
                return ResourceManager.GetString("lblSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar este adjunto?.
        /// </summary>
        internal static string msgConfirmarEliminacionAdjunto {
            get {
                return ResourceManager.GetString("msgConfirmarEliminacionAdjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un archivo..
        /// </summary>
        internal static string msgMustSelectFile {
            get {
                return ResourceManager.GetString("msgMustSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un registro.
        /// </summary>
        internal static string msgRequiredRowSelected {
            get {
                return ResourceManager.GetString("msgRequiredRowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del archivo.
        /// </summary>
        internal static string NombreArchivo {
            get {
                return ResourceManager.GetString("NombreArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar adjunto.
        /// </summary>
        internal static string titleDownloadFile {
            get {
                return ResourceManager.GetString("titleDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar adjunto.
        /// </summary>
        internal static string titleRemoveFile {
            get {
                return ResourceManager.GetString("titleRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción cancelada..
        /// </summary>
        internal static string TransacCanceled {
            get {
                return ResourceManager.GetString("TransacCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se canceló la solicitud..
        /// </summary>
        internal static string TransacCanceledDetail {
            get {
                return ResourceManager.GetString("TransacCanceledDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción procesada..
        /// </summary>
        internal static string TransacProcessed {
            get {
                return ResourceManager.GetString("TransacProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación fue realizada con éxito..
        /// </summary>
        internal static string TransacProcessedDetail {
            get {
                return ResourceManager.GetString("TransacProcessedDetail", resourceCulture);
            }
        }
    }
}
