//------------------------------------------------------------------------------
// <auto-generated>
//   Este codigo fue generado por Pectra Forms
// 
//   Cambios en este archivo pueden ocasionar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

using PectraForms.WebApplication.BackEnd.BusinessEntities;

namespace PectraForms.WebApplication.Models
{
    public class _BaseViewModel
    {
        public string TrxId { get; set; }
        public PectraAttributesBE PectraAttributes { get; set; }
    }
}