//------------------------------------------------------------------------------
// <auto-generated>
//   Este codigo fue generado por Pectra Forms
// 
//   Cambios en este archivo pueden ocasionar un comportamiento incorrecto.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PectraForms.WebApplication.Models
{
    public class TransactionCompletedViewModel
    {
        public string Message { get; set; }
        public string MessageDetail { get; set; }
    }
}